In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
# Initialise a new model to work with
model = tf.keras.Sequential()

# Add an input layer for 8 features to give to the network
model.add(tf.keras.layers.InputLayer(input_shape=(8,), name='Input_layer'))

# Add 2 dense layers to process the inputs, with one being hidden and the other giving the final output
model.add(tf.keras.layers.Dense(4, activation='relu', name='First_hidden_layer'))
model.add(tf.keras.layers.Dense(1, name='Output_layer'))

# View the weights of the model
model.variables

[<tf.Variable 'First_hidden_layer/kernel:0' shape=(8, 4) dtype=float32, numpy=
 array([[-0.36910355, -0.69027686,  0.69722885,  0.24909377],
        [ 0.27746195,  0.6696333 ,  0.11030674, -0.38193542],
        [ 0.06975335, -0.6099119 , -0.6521555 , -0.05586499],
        [ 0.07234609, -0.14146554, -0.29602596,  0.5215321 ],
        [-0.1382314 ,  0.29100728, -0.34561375,  0.65997785],
        [ 0.18725371, -0.12474352,  0.65251917, -0.29541922],
        [-0.66865385, -0.57498384,  0.63650316, -0.2239761 ],
        [-0.0538404 ,  0.2604503 ,  0.37435585, -0.0189575 ]],
       dtype=float32)>,
 <tf.Variable 'First_hidden_layer/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'Output_layer/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 0.40661812],
        [ 0.00745654],
        [ 0.36078298],
        [-0.99815035]], dtype=float32)>,
 <tf.Variable 'Output_layer/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [3]:
# Generate 32 sets of randomised data to feed to the network
data = tf.random.normal((32,8))
# Feed the features to the network to see its output based on the initial values given on creation
prediction = model.predict(data)
prediction

1/1 [==============================] - 0s 398ms/step


array([[-1.1032779e+00],
       [ 4.2162031e-01],
       [-4.3523139e-01],
       [ 7.3375389e-02],
       [-1.5254205e+00],
       [-1.1167034e+00],
       [ 3.5439479e-01],
       [-1.7889062e-01],
       [ 5.7503492e-01],
       [ 4.5472589e-01],
       [-1.6081361e+00],
       [-3.9884302e-01],
       [ 3.5069779e-02],
       [-5.1726043e-01],
       [ 1.1570751e-01],
       [-1.0408831e+00],
       [-5.0551397e-01],
       [ 1.5697797e-03],
       [-1.9506951e-01],
       [ 5.2839473e-02],
       [ 4.5387247e-01],
       [ 5.4315728e-01],
       [ 3.0088943e-01],
       [-8.5930234e-01],
       [-2.3662512e+00],
       [-1.8470711e-01],
       [-1.3887535e+00],
       [ 6.6189015e-01],
       [-7.6399708e-01],
       [ 9.4987947e-01],
       [ 5.4650211e-01],
       [-2.7191120e-01]], dtype=float32)