In [7]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
# Initialising an integer as a TensorFlow variable
int_variable = tf.Variable(4113, tf.int16)
int_variable

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4113>

In [3]:
tf.rank(int_variable)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
# Showing the rank of the variable as an integer
tf.rank(int_variable).numpy()

0

In [5]:
# `int_variable` is a scalar value, so it has no shape
int_variable.shape

TensorShape([])

In [6]:
int_variable.shape.as_list()

[]

In [8]:
# Example of a Vector as a Tensorflow Variable - in this case, the votes for 3 different candidates
vector_variable = tf.Variable([0.23, 0.42, 0.35], tf.float32)
vector_variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([0.23, 0.42, 0.35], dtype=float32)>

In [9]:
# The vector has 1 dimension
tf.rank(vector_variable).numpy()

1

In [10]:
# And has 3 items within that dimension
vector_variable.shape.as_list()

[3]

In [11]:
# Creating a matrix for the candidates across different districts
matrix_variable = tf.Variable([[4113, 7511, 6259], [3870, 6725, 6962]], tf.int32)
matrix_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[4113, 7511, 6259],
       [3870, 6725, 6962]])>

In [12]:
# This matrix has 2 dimensions - one for votes, and another to separate each district
tf.rank(matrix_variable).numpy()

2

In [13]:
# The matrix shows the 3 parties in 2 districts
matrix_variable.shape.as_list()

[2, 3]

In [14]:
# This tensor has 3 dimensions - Votes for 3 different candidates in 2 districts, across 3 parties
tensor_variable = tf.Variable([[[4113, 7511, 6259], 
                                [3870, 6725, 6962]], 
                               [[5102, 7038, 6591], 
                                [3661, 5901, 6235]], 
                               [[951, 1208, 1098], 
                                [870, 645, 948]]])
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[4113, 7511, 6259],
        [3870, 6725, 6962]],

       [[5102, 7038, 6591],
        [3661, 5901, 6235]],

       [[ 951, 1208, 1098],
        [ 870,  645,  948]]])>

In [15]:
tf.rank(tensor_variable).numpy()

3

In [16]:
tensor_variable.shape.as_list()

[3, 2, 3]