In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
product_a_salesperson_1 = tf.Variable(2706, tf.int16)
product_a_salesperson_2 = tf.Variable(2386, tf.int16)
product_a_location_x_total = product_a_salesperson_1 + product_a_salesperson_2
product_a_location_x_total

<tf.Tensor: shape=(), dtype=int32, numpy=5092>

In [3]:
salesperson_1_sales = tf.Variable([2706, 2799, 5102], tf.int16)
# The goal is to sell 95 units of each product
day_sales_goal = tf.Variable(95, tf.int16)
salesperson_1_goal = salesperson_1_sales + day_sales_goal
# Print the goal for the day (with that being the total sold so far plus the 95 that are aimed to be sold of each product today)
salesperson_1_goal

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2801, 2894, 5197])>

In [4]:
# Creating 3 tensors, with each one representing the sales in a location, with each row being a different salesperson
location_x_sales = tf.Variable(
    [
        [2706, 2799, 5102],
        [2386, 4089, 5932]
    ],
    
    tf.int16
)

location_y_sales = tf.Variable(
    [
        [5901, 1208, 645],
        [6235, 1098, 948]
    ],
    
    tf.int16
)

location_z_sales = tf.Variable(
    [
        [3908, 2339, 5520],
        [4544, 1978, 4729]
    ],
    
    tf.int16
)
# Sum total product sales across all locations
total_sales = location_x_sales + location_y_sales + location_z_sales
total_sales

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12515,  6346, 11267],
       [13165,  7165, 11609]])>