In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
matrix1 = tf.Variable([[1,2,3,4], [5,6,7,8]])
matrix1.shape.as_list()

[2, 4]

In [3]:
reshape1 = tf.reshape(matrix1, shape=[4, 2])
reshape1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])>

In [4]:
reshape1.shape.as_list()

[4, 2]

In [5]:
reshape2 = tf.reshape(matrix1, [1, 8])
reshape2

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6, 7, 8]])>

In [6]:
reshape3 = tf.reshape(matrix1, [8, 1])
reshape3

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])>

In [7]:
# Reshaping to make the original matrix a 3-dimensional tensor
reshape4 = tf.reshape(matrix1, [2, 2, 2])
reshape4

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [8]:
reshape4.shape.as_list()

[2, 2, 2]

In [9]:
# Confirm reshaped tensor has 3 dimensions
tf.rank(reshape4).numpy()

3

In [10]:
transpose1 = tf.transpose(matrix1)
transpose1

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

In [11]:
# Transposing a tensor and reshaping it to the same shape do *not* have the same output tensor
transpose1 == reshape1

<tf.Tensor: shape=(4, 2), dtype=bool, numpy=
array([[ True, False],
       [False, False],
       [False, False],
       [False,  True]])>

In [12]:
transpose2 = tf.transpose(reshape4)
transpose2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])>