In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
increasing_list = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
increasing_list.shape

TensorShape([24])

In [10]:
# Make matrix of 2 items in each list
reshaped_matrix = tf.reshape(increasing_list, [12, 2])
reshaped_matrix

<tf.Tensor: shape=(12, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])>

In [4]:
# Reshape 24 items into 3-dimensional tensor
reshaped_tensor = tf.reshape(increasing_list, [3, 4, 2])
reshaped_tensor

<tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])>

In [5]:
reshaped_tensor.shape

TensorShape([3, 4, 2])

In [8]:
tf.rank(reshaped_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [11]:
transposed_matrix = tf.transpose(reshaped_matrix)
transposed_matrix

<tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24]])>

In [12]:
# The dimensions of the axes are reversed when transposing
transposed_matrix.shape

TensorShape([2, 12])