In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [3]:
tensor1 = tf.Variable([[1,2,3]])
tensor2 = tf.Variable([[1],[2],[3]])
tensor_mult = tf.matmul(tensor1, tensor2)
tensor_mult

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

In [4]:
# The `@` operator can be used to multiply tensors
tensor_mult_operator = tensor1 @ tensor2
tensor_mult_operator

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]])>

In [5]:
# Scalar multiplication will multiply all elements by the scalar value
tensor1 = tf.Variable([[1,2,3]])
scalar_mult = 5 * tensor1
scalar_mult

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 5, 10, 15]])>