In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
# Matrix that represents the amount of ingredients needed for each recipe
matrix1 = tf.Variable([[1.0,0.0,3.0,1.0,2.0], 
                       [0.0,1.0,1.0,1.0,1.0], 
                       [2.0,1.0,0.0,2.0,0.0]], tf.float32)
matrix1

<tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
array([[1., 0., 3., 1., 2.],
       [0., 1., 1., 1., 1.],
       [2., 1., 0., 2., 0.]], dtype=float32)>

In [3]:
# Matrix representing the costs and weights of each ingredient
matrix2 = tf.Variable([[0.49, 103], 
                       [0.18, 38], 
                       [0.24, 69], 
                       [1.02, 75], 
                       [0.68, 78]])

matrix2

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[  0.49, 103.  ],
       [  0.18,  38.  ],
       [  0.24,  69.  ],
       [  1.02,  75.  ],
       [  0.68,  78.  ]], dtype=float32)>

In [4]:
# Multiplying the ingredient amounts to use by costs and weights
matmul1 = tf.matmul(matrix1, matrix2)
matmul1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[  3.5900002, 541.       ],
       [  2.1200001, 260.       ],
       [  3.2      , 394.       ]], dtype=float32)>

In [6]:
# Matrix representing number of each type of sandwich sold between 5 stores
matrix3 = tf.Variable([[120.0, 100.0, 90.0], 
                       [30.0, 15.0, 20.0], 
                       [220.0, 240.0, 185.0], 
                       [145.0, 160.0, 155.0], 
                       [330.0, 295.0, 290.0]])
# Get expected costs and weights of ingredients for each store
matmul2 = matrix3 @ matmul1
matmul2

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[9.3080005e+02, 1.2638000e+05],
       [2.0350000e+02, 2.8010000e+04],
       [1.8906001e+03, 2.5431000e+05],
       [1.3557501e+03, 1.8111500e+05],
       [2.7381001e+03, 3.6949000e+05]], dtype=float32)>