In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [2]:
sales_records = tf.Variable([[-0.013, 0.024, 0.06, 0.022], 
                             [0.001, -0.047, 0.039, 0.016], 
                             [0.018, 0.030, -0.021, -0.028]])
sales_records

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.013,  0.024,  0.06 ,  0.022],
       [ 0.001, -0.047,  0.039,  0.016],
       [ 0.018,  0.03 , -0.021, -0.028]], dtype=float32)>

In [3]:
car_values = tf.Variable([[19995.95], [24995.50], [36745.50], [29995.95]])
car_values

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[19995.95],
       [24995.5 ],
       [36745.5 ],
       [29995.95]], dtype=float32)>

In [4]:
biases = tf.Variable([[-2500.0], [-2500.0], [-2500.0]])
biases

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-2500.],
       [-2500.],
       [-2500.]], dtype=float32)>

In [6]:
msrp_deviation = sales_records @ car_values
msrp_deviation

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[3204.5854 ],
       [ 758.2173 ],
       [-501.75012]], dtype=float32)>

In [7]:
deviation_without_costs = msrp_deviation + biases
deviation_without_costs

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[  704.58545],
       [-1741.7827 ],
       [-3001.75   ]], dtype=float32)>

In [8]:
# The ReLU function will clamp negative values to 0, keeping only salespeople that overall made a profit
positive_only = tf.keras.activations.relu(deviation_without_costs)
positive_only

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[704.58545],
       [  0.     ],
       [  0.     ]], dtype=float32)>