In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [3]:
df = tf.data.experimental.make_csv_dataset('drugsCom_raw/drugsComTest_raw.tsv', batch_size=1, field_delim='\t')
df

<_PrefetchDataset element_spec=OrderedDict([('', TensorSpec(shape=(1,), dtype=tf.int32, name=None)), ('drugName', TensorSpec(shape=(1,), dtype=tf.string, name=None)), ('condition', TensorSpec(shape=(1,), dtype=tf.string, name=None)), ('review', TensorSpec(shape=(1,), dtype=tf.string, name=None)), ('rating', TensorSpec(shape=(1,), dtype=tf.float32, name=None)), ('date', TensorSpec(shape=(1,), dtype=tf.string, name=None)), ('usefulCount', TensorSpec(shape=(1,), dtype=tf.int32, name=None))])>

In [6]:
def prep_ds(ds, shuffle_buffer_size=1024, batch_size=32):
    # Shuffle the dataset
    ds = ds.shuffle(buffer_size=shuffle_buffer_size)
    # Repeat the dataset
    ds = ds.repeat()
    # Batch the dataset
    ds = ds.batch(batch_size)

    return ds

ds = prep_ds(df, batch_size=5)

# Print the first item in the batch
for x in ds.take(1):
    print(x)

OrderedDict([('', <tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 45625],
       [ 16584],
       [205577],
       [134367],
       [203783]])>), ('drugName', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Fluoxetine'],
       [b'Ethinyl estradiol / norethindrone'],
       [b'Pristiq'],
       [b'Prednisone'],
       [b'Suvorexant']], dtype=object)>), ('condition', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'Depression'],
       [b'Birth Control'],
       [b'Depression'],
       [b'Gouty Arthritis'],
       [b'Insomnia']], dtype=object)>), ('review', <tf.Tensor: shape=(5, 1), dtype=string, numpy=
array([[b'"Started on 10mg while seeing a mental health professional (counselor) simultaneously. Medicine kicked in at about 3 weeks of treatment and got better when MD increased the dosage to 20 mg 6 weeks into treatment. It&#039;s been a consistent once daily oral capsule 20 mg for the past 3 1/2 months. Mood has lifted. Wakes up with clear thoughts. Lessened ra

In [7]:
import tensorflow_hub as hub

# Load and pass an item from the dataset through the pretrained model
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"

hub_layer = hub.KerasLayer(embedding, input_shape=[], dtype=tf.string, trainable=True)

for x in ds.take(1):
    print(hub_layer(tf.reshape(x['review'],[-1])))

tf.Tensor(
[[ 0.9881613  -2.8450797   1.2315621   0.09081963 -2.4110882  -3.927364
  -1.8330681   0.39639175  0.7191831  -0.39629233 -0.24139255  2.374047
   0.1731554   0.33019003 -3.418654    1.8822201   3.45956    -1.9857818
  -1.1341906  -1.4296856 ]
 [ 0.5661839  -2.7838304   0.9755192   0.02443876 -2.1842694  -3.212697
  -1.599586    1.3337802   2.561705    1.1625223  -1.9061416   0.8155015
   0.1338313   0.5315414  -3.8749793   1.5308723   2.672744   -1.6771619
  -0.6530117  -0.26535785]
 [ 1.0484432  -3.3830547   1.3292578   1.0691189  -3.8926852  -4.819075
  -2.0403776   2.2565262   3.0522056   1.1546133  -1.5194812   1.7076561
  -0.05522209  0.76448995 -5.405298    2.0072222   4.1093802  -2.4143872
  -2.3503373  -1.360385  ]
 [ 2.4830527  -1.0085537   0.84112895  1.8802489  -2.1662912  -1.8582801
  -0.634127    1.0757595  -0.7597292  -1.6074272  -0.6742036   3.413891
  -0.6005693   0.2735835  -2.0015898   0.8834489   2.5047452  -0.85837126
  -1.2960104  -1.711054  ]
 [ 1.3926